// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service/protos/queryPrinter.proto

package protos

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Request) Validate() error {
	return nil
}
func (this *Response) Validate() error {
	return nil
}
